apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb-alerts
  labels:
    release: prometheus # 이게 제일 중요!!!
spec:
  groups:
    - name: mongodb
      rules:
        - alert: MongodbTooManyConnections
          expr: (mongodb_connections_current / mongodb_connections_available) * 100 >= 80
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: MongoDB too many connections (instance {{ $labels.instance }})
            description: "Too many connections (>= 80%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: MongodbAssertsNotZero
          expr: mongodb_asserts_msg + mongodb_asserts_regular + mongodb_asserts_rollovers + mongodb_asserts_tripwire + mongodb_asserts_warning > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MongoDB Asserts metric non-zero (instance {{ $labels.instance }})
            description: "MongoDB Asserts metric non-zero\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: MongodbTooMuchCache
          expr: (mongodb_wiredTiger_cache_bytes_currently_in_the_cache / mongodb_wiredTiger_cache_maximum_bytes_configured) * 100 >= 0.7
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: MongoDB too much cache (instance {{ $labels.instance }})
            description: "Too much cache (>= 0.7%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"