apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mongodb-alerts
  labels:
    release: prometheus # 이게 제일 중요!!!
spec:
  groups:
    - name: mongodb
      rules:
        - alert: MongodbDown
          expr: mongodb_up == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MongoDB Down (instance {{ $labels.instance }})
            description: "MongoDB instance is down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: MongodbTooManyConnections
          expr: mongodb_connections_current / mongodb_connections_available >= 0.2
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: MongoDB too many connections (instance {{ $labels.instance }})
            description: "Too many connections (>= 80%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: MongodbAssertsNotZero
          expr: mongodb_asserts_msg + mongodb_asserts_regular + mongodb_asserts_rollovers + mongodb_asserts_tripwire + mongodb_asserts_warning > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: MongoDB Asserts metric non-zero (instance {{ $labels.instance }})
            description: "MongoDB Asserts metric non-zero\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"